name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Run compile
      run: sbt compile
    - name: Run publish
      run: sbt docker:publish
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIV_KEY }}
        known_hosts: unnecessary
    - name: Spin Up
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -oStrictHostKeyChecking=no "cd elabsheet && docker-compose stop && docker-compose pull && docker-compose up -d"
        
